#!/usr/bin/env bash
#the beautiful fizzbuzz

x=1
y=3
z=5

while [ $x -le 100 ]
do
	if [ $((x%z)) == 0 ] && [ $((x%y)) == 0 ]
	then
		echo "FizzBuzz"
	elif [ $((x%y)) == 0 ]
	then
		echo "Fizz"
	elif [ $((x%z)) == 0 ]
	then
		echo "Buzz"
	else
		echo $x
	fi
	x=$(( x + 1 ))
done	
