#!/usr/bin/env bash
Script will connect to a server whose ip address is 100.24.255.199 and username is ubuntu

private_key = ~/.ssh/school
user = ubuntu
server_address = 100.24.255.199

ssh -i "$private_key" "user@$server_address"
